name: C Build

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Install GCC
        run: sudo apt-get update && sudo apt-get install -y gcc

      - name: Compile C Program
        run: gcc c5.c -o c5

      - name: Run Program
        run: ./c5